### ISSUE TITLE
Outputs are being mutated when they shouldn't

### ISSUE THREAD

**Issue by christianechevarria** [liquidcarrot/carrot#51]
**Describe the bug**
Output is not remaining normalized

**To Reproduce**
Current settings:
```
Methods.mutation.MOD_ACTIVATION.mutateOutput = false;
Methods.mutation.SWAP_NODES.mutateOutput = false;
```

**Expected behavior**
- Outputs remain normalized when mutateOutput is set to false.
- Default behavior is to keep output normalized

**Screenshots**
![Screenshot 2019-05-04 at 10 26 12 AM](https://user-images.githubusercontent.com/23618650/57180531-62c81280-6e57-11e9-91b9-51fcb9cd160e.png)

**Comment by christianechevarria** [comment]
Looks like this is happening because there's currently no check or differentiation between input / hidden nodes and output nodes. This is the current code inside network.mutate for example:

```
case mutation.MOD_ACTIVATION:
        // Has no effect on input node, so they (should be, but aren't necessarily ) excluded
        if (!method.mutateOutput && this.input + this.output === this.nodes.length) {
          if (config.warnings) console.warn('No nodes that allow mutation of activation function');
          break;
        }

        var index = Math.floor(Math.random() * (this.nodes.length - (method.mutateOutput ? 0 : this.output) - this.input) + this.input);
        var node = this.nodes[index];

        node.mutate(method);
        break;
```

We're randomly picking an index and not checking to see if the selected node is an input or output neuron which, of course, results in some probability of output neurons being mutated.

For reference here is the SWAP_NODES case too:

```
case mutation.SWAP_NODES:
        // Has no effect on input node, so they (should be) excluded
        if ((method.mutateOutput && this.nodes.length - this.input < 2) ||
          (!method.mutateOutput && this.nodes.length - this.input - this.output < 2)) {
          if (config.warnings) console.warn('No nodes that allow swapping of bias and activation function');
          break;
        }

        var index = Math.floor(Math.random() * (this.nodes.length - (method.mutateOutput ? 0 : this.output) - this.input) + this.input);
        var node1 = this.nodes[index];
        index = Math.floor(Math.random() * (this.nodes.length - (method.mutateOutput ? 0 : this.output) - this.input) + this.input);
        var node2 = this.nodes[index];

        var biasTemp = node1.bias;
        var squashTemp = node1.squash;

        node1.bias = node2.bias;
        node1.squash = node2.squash;
        node2.bias = biasTemp;
        node2.squash = squashTemp;
        break;
    }
```

Some possible solutions:
- Add a check for node.type, try a new indexes when output nodes are found **easy to implement but not the most performant**
- Re-architect Network to house input & output neurons within Network.input & Network.output respectively. This cuts down on checks during various for loops and still allows us to treat all 3 arrays (input, output, and hidden) as one for situations that require that behavior **more performant, but also more complex to implement and maintain**

Any input on this would be highly appreciated!

**Comment by christianechevarria** [comment]
This one should fix it: ea01662193472e69b41cd0088db9d344aa90b68e

There was a stray location variable that was removed in: 026202076f51b8f83d3c368bfc005f723cbb5537

**Comment by dan-ryan** [comment]
@christianechevarria I'm still getting values more than 1. So not totally fixed.

**Comment by luiscarbonell** [comment]
@dan-ryan Are you still having this issue? 

I can't replicate it on my end anymore.

Code snippet?

**Comment by dan-ryan** [comment]
The code I gave before not doing it? I didn't get it last night with my latest script. I'll try repeating it.

**Comment by christianechevarria** [comment]
Hey guys! Just wanted to see if there were any updates on the status of this as a bug?

**Comment by dan-ryan** [comment]
I'll try the latest changes and see if it has changed anything.

**Comment by dan-ryan** [comment]
Since I can't run the latest build without crashing while evolving, testing will have to wait.

**Comment by luiscarbonell** [comment]
@dan-ryan The tests were running fine on our end now - are you still running into the issue?

**Comment by dan-ryan** [comment]
Yes: https://github.com/liquidcarrot/carrot/issues/115

**Comment by christianechevarria** [comment]
@dan-ryan wanted to circle back on this one as part of the #115 dependent issues, is this still a problem that's happening?

We're currently unable to reproduce it

**Comment by dan-ryan** [comment]
I had some issues with yesterdays testing with values not being normalised. But it might be because I was still having trouble with #115

**Comment by christianechevarria** [comment]
Circling back on this, it's possible that output neurons are not actually mutated, but network might be outputting un-normalized output anyway due to issues caused by #34 

I've added a fix for #34 in 71301ba7c4ac68c86f934cf7efac3604982bfce3 and I'd be curious to find out if it also solves this issue too

**Comment by christianechevarria** [comment]
Just discovered an `ADD_NODE` mutation bug that converts outputs into hidden nodes while writing tests:

https://github.com/liquidcarrot/carrot/issues/163#issuecomment-536233679
